package View;

import Controller.CJanela;
import Controller.MembrosDAO;
import Controller.PlanosDAO;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.sql.SQLException;

/**
 *
 * @author Roneide
 */
public class CadastrarAluno extends javax.swing.JFrame {

    private final MembrosDAO dao = new MembrosDAO();
    public CadastrarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNomeCadAlu = new javax.swing.JTextField();
        tfCPFCadAlu = new javax.swing.JTextField();
        tfPhoneCadAlu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEndereco = new javax.swing.JTextArea();
        btCadastrarCadAluno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboxPlano = new javax.swing.JComboBox<>();
        menuBarSecretaria = new javax.swing.JMenuBar();
        mbRecepcionar = new javax.swing.JMenu();
        miGerAlu = new javax.swing.JMenuItem();
        miRegPag = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE ALUNOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Telefone");

        tfNomeCadAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfCPFCadAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfPhoneCadAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Plano");

        taEndereco.setColumns(20);
        taEndereco.setRows(5);
        jScrollPane1.setViewportView(taEndereco);

        btCadastrarCadAluno.setBackground(new java.awt.Color(255, 204, 0));
        btCadastrarCadAluno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCadastrarCadAluno.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarCadAluno.setText("CADASTRAR");
        btCadastrarCadAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCadastrarCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarCadAlunoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Endereço");

        cboxPlano.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboxPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diária", "Plano SE Mensal", "Plano Black", "Plano Black Anual" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCadastrarCadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(414, 414, 414))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCPFCadAlu)
                                    .addComponent(tfNomeCadAlu)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPhoneCadAlu)
                                    .addComponent(cboxPlano, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(122, 122, 122))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNomeCadAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCPFCadAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPhoneCadAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cboxPlano)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addComponent(btCadastrarCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        mbRecepcionar.setText("Secretaria");

        miGerAlu.setText("Gerenciar Aluno");
        miGerAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerAluActionPerformed(evt);
            }
        });
        mbRecepcionar.add(miGerAlu);

        miRegPag.setText("Registrar Pagamentos");
        mbRecepcionar.add(miRegPag);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbRecepcionar.add(miVoltar);

        menuBarSecretaria.add(mbRecepcionar);

        setJMenuBar(menuBarSecretaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miGerAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerAluActionPerformed
GerenciarAluno geralu = new GerenciarAluno();
CJanela.abrir(geralu, "Tela de Gerenciar Alunos", this);
this.dispose();
    }//GEN-LAST:event_miGerAluActionPerformed

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void btCadastrarCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarCadAlunoActionPerformed
        cadastrarAluno();
        limparCampos();
    }//GEN-LAST:event_btCadastrarCadAlunoActionPerformed

    private void cadastrarAluno() {
    try {

        String nome = tfNomeCadAlu.getText();
        String cpf = tfCPFCadAlu.getText();
        String telefone = tfPhoneCadAlu.getText();
        String endereco = taEndereco.getText();
        String nomePlano = (String) cboxPlano.getSelectedItem();
        
        int id_plano = PlanosDAO.obterIdPorNome(nomePlano);
        
        dao.cadastrarAluno(nome, cpf, telefone, endereco, id_plano);
        
        JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
    }
}
    
    private void limparCampos() {
    tfNomeCadAlu.setText("");
    tfCPFCadAlu.setText("");
    tfPhoneCadAlu.setText("");
    taEndereco.setText("");
    cboxPlano.setSelectedIndex(0);
}
    
    
    
    
    
    
    
    public JButton getBtCadastrarCadAluno() {
        return btCadastrarCadAluno;
    }

    public void setBtCadastrarCadAluno(JButton btCadastrarCadAluno) {
        this.btCadastrarCadAluno = btCadastrarCadAluno;
    }

    public JComboBox<String> getCboxPlano() {
        return cboxPlano;
    }

    public void setCboxPlano(JComboBox<String> cboxPlano) {
        this.cboxPlano = cboxPlano;
    }

    public JTextArea getTaEndereco() {
        return taEndereco;
    }

    public void setTaEndereco(JTextArea taEndereco) {
        this.taEndereco = taEndereco;
    }

    public JTextField getTfCPFCadAlu() {
        return tfCPFCadAlu;
    }

    public void setTfCPFCadAlu(JTextField tfCPFCadAlu) {
        this.tfCPFCadAlu = tfCPFCadAlu;
    }

    public JTextField getTfNomeCadAlu() {
        return tfNomeCadAlu;
    }

    public void setTfNomeCadAlu(JTextField tfNomeCadAlu) {
        this.tfNomeCadAlu = tfNomeCadAlu;
    }

    public JTextField getTfPhoneCadAlu() {
        return tfPhoneCadAlu;
    }

    public void setTfPhoneCadAlu(JTextField tfPhoneCadAlu) {
        this.tfPhoneCadAlu = tfPhoneCadAlu;
    }

    
   
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarCadAluno;
    private javax.swing.JComboBox<String> cboxPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbRecepcionar;
    private javax.swing.JMenuBar menuBarSecretaria;
    private javax.swing.JMenuItem miGerAlu;
    private javax.swing.JMenuItem miRegPag;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTextArea taEndereco;
    private javax.swing.JTextField tfCPFCadAlu;
    private javax.swing.JTextField tfNomeCadAlu;
    private javax.swing.JTextField tfPhoneCadAlu;
    // End of variables declaration//GEN-END:variables
}
