/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CJanela;
import Controller.FuncionariosDAO;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Roneide
 */
public class CadastrarFuncionario extends javax.swing.JFrame {

   private final FuncionariosDAO dao = new FuncionariosDAO();
    public CadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNomeCadFun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCPFCadFun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfLoginCadFun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfSenhaCadFun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboxCargoCadFun = new javax.swing.JComboBox<>();
        btCadastrarFun = new javax.swing.JButton();
        menuBarGerente = new javax.swing.JMenuBar();
        mbGerenciar = new javax.swing.JMenu();
        miGerFun = new javax.swing.JMenuItem();
        miGerPlan = new javax.swing.JMenuItem();
        miHisPa = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE FUNCIONÁRIOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nome");

        tfNomeCadFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNomeCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeCadFunActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("CPF");

        tfCPFCadFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Login");

        tfLoginCadFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfLoginCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginCadFunActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Senha");

        tfSenhaCadFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSenhaCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaCadFunActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Cargo");

        cboxCargoCadFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxCargoCadFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretário", "Personal Trainer", "Gerente", "Assistente Geral" }));

        btCadastrarFun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCadastrarFun.setText("Cadastrar Funcionário");
        btCadastrarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarFunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCPFCadFun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomeCadFun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSenhaCadFun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxCargoCadFun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLoginCadFun)
                                .addGap(6, 6, 6))
                            .addComponent(btCadastrarFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(tfNomeCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCPFCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(tfLoginCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tfSenhaCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxCargoCadFun, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastrarFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        mbGerenciar.setText("Gerenciar");

        miGerFun.setText("Gerenciar Funcionário");
        miGerFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerFunActionPerformed(evt);
            }
        });
        mbGerenciar.add(miGerFun);

        miGerPlan.setText("Gerenciar Planos");
        miGerPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerPlanActionPerformed(evt);
            }
        });
        mbGerenciar.add(miGerPlan);

        miHisPa.setText("Histórico de Pagamentos");
        miHisPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHisPaActionPerformed(evt);
            }
        });
        mbGerenciar.add(miHisPa);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbGerenciar.add(miVoltar);

        menuBarGerente.add(mbGerenciar);

        setJMenuBar(menuBarGerente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeCadFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeCadFunActionPerformed

    private void tfLoginCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginCadFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoginCadFunActionPerformed

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void miGerFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerFunActionPerformed
    GerenciarFuncionario geren = new GerenciarFuncionario();
CJanela.abrir(geren,"Tela de Gerênciar Funcionários", this);
    }//GEN-LAST:event_miGerFunActionPerformed

    private void btCadastrarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarFunActionPerformed
 cadastrarFuncionario();
 limparCaixa();
    }//GEN-LAST:event_btCadastrarFunActionPerformed

    private void tfSenhaCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaCadFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSenhaCadFunActionPerformed

    private void miGerPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerPlanActionPerformed
 GerenciarPlanos gerplan = new GerenciarPlanos();
 CJanela.abrir(gerplan, "Tela de Gerenciamento de Planos", this);
 this.dispose();
    }//GEN-LAST:event_miGerPlanActionPerformed

    private void miHisPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHisPaActionPerformed
HistoricoPagamentos hispa = new HistoricoPagamentos();
CJanela.abrir(hispa, "Tela de Gerenciamento de Planos", this);
this.dispose();
    }//GEN-LAST:event_miHisPaActionPerformed

    
    
    private void cadastrarFuncionario(){
        try{
            String nome = tfNomeCadFun.getText();
            String cpf = tfCPFCadFun.getText();
            String login = tfLoginCadFun.getText();
            String senha = tfSenhaCadFun.getText();
            String cargo = cboxCargoCadFun.getSelectedItem().toString(); 
            dao.cadastrarFuncionario(nome, cpf, login, senha, cargo);
            JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso, o Deseje Boas-Vindas!");
            
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
    }
    }
    
    private void limparCaixa(){
    tfNomeCadFun.setText("");
    tfCPFCadFun.setText("");
    tfLoginCadFun.setText("");
    tfSenhaCadFun.setText("");
    cboxCargoCadFun.setSelectedIndex(3);
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public JButton getBtCadastrarFun() {
        return btCadastrarFun;
    }

    public void setBtCadastrarFun(JButton btCadastrarFun) {
        this.btCadastrarFun = btCadastrarFun;
    }

    public JComboBox<String> getCboxCargoCadFun() {
        return cboxCargoCadFun;
    }

    public void setCboxCargoCadFun(JComboBox<String> cboxCargoCadFun) {
        this.cboxCargoCadFun = cboxCargoCadFun;
    }

    public JTextField getTfCPFCadFun() {
        return tfCPFCadFun;
    }

    public void setTfCPFCadFun(JTextField tfCPFCadFun) {
        this.tfCPFCadFun = tfCPFCadFun;
    }

    public JTextField getTfLoginCadFun() {
        return tfLoginCadFun;
    }

    public void setTfLoginCadFun(JTextField tfLoginCadFun) {
        this.tfLoginCadFun = tfLoginCadFun;
    }

    public JTextField getTfNomeCadFun() {
        return tfNomeCadFun;
    }

    public void setTfNomeCadFun(JTextField tfNomeCadFun) {
        this.tfNomeCadFun = tfNomeCadFun;
    }

    public JTextField getTfSenhaCadFun() {
        return tfSenhaCadFun;
    }

    public void setTfSenhaCadFun(JTextField tfSenhaCadFun) {
        this.tfSenhaCadFun = tfSenhaCadFun;
    }

  
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarFun;
    private javax.swing.JComboBox<String> cboxCargoCadFun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mbGerenciar;
    private javax.swing.JMenuBar menuBarGerente;
    private javax.swing.JMenuItem miGerFun;
    private javax.swing.JMenuItem miGerPlan;
    private javax.swing.JMenuItem miHisPa;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTextField tfCPFCadFun;
    private javax.swing.JTextField tfLoginCadFun;
    private javax.swing.JTextField tfNomeCadFun;
    private javax.swing.JTextField tfSenhaCadFun;
    // End of variables declaration//GEN-END:variables
}
