/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CJanela;
import Controller.FazTudo;
import Controller.FuncionariosDAO;
import Controller.STabela;
import Model.Funcionario;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Roneide
 */
public class GerenciarFuncionario extends javax.swing.JFrame {

    
    
    private final FuncionariosDAO dao = new FuncionariosDAO();
private final STabela tabela = new STabela();
    
    public GerenciarFuncionario() {
        initComponents();
        tabelar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFun = new javax.swing.JTable();
        btDelFun = new javax.swing.JButton();
        btAtualizarFun = new javax.swing.JButton();
        btBuscarFun = new javax.swing.JButton();
        tfIdFun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfNomeGerFun = new javax.swing.JTextField();
        tfCPFGerFun = new javax.swing.JTextField();
        tfLoginGerFun = new javax.swing.JTextField();
        tfSenhaGerFun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboxCargoGerFun = new javax.swing.JComboBox<>();
        menuBarGerente = new javax.swing.JMenuBar();
        mbGerenciar = new javax.swing.JMenu();
        miCadFun = new javax.swing.JMenuItem();
        miGerPlan = new javax.swing.JMenuItem();
        miHisPa = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Cargo", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFun);
        if (tabelaFun.getColumnModel().getColumnCount() > 0) {
            tabelaFun.getColumnModel().getColumn(2).setResizable(false);
            tabelaFun.getColumnModel().getColumn(5).setResizable(false);
        }

        btDelFun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDelFun.setText("Deletar Funcionário");
        btDelFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelFunActionPerformed(evt);
            }
        });

        btAtualizarFun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAtualizarFun.setText("Atualizar Funcionário");
        btAtualizarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarFunActionPerformed(evt);
            }
        });

        btBuscarFun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBuscarFun.setText("Buscar Funcionário");
        btBuscarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarFunActionPerformed(evt);
            }
        });

        tfIdFun.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INFORME O ID  DO FUNCIONÁRIO");

        tfNomeGerFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNomeGerFun.setForeground(new java.awt.Color(102, 102, 102));

        tfCPFGerFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfCPFGerFun.setForeground(new java.awt.Color(102, 102, 102));

        tfLoginGerFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfLoginGerFun.setForeground(new java.awt.Color(102, 102, 102));

        tfSenhaGerFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSenhaGerFun.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Login");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Senha");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("GERENCIAR FUNCIONARIOS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nome");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("CPF");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Cargo");

        cboxCargoGerFun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxCargoGerFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretário", "Personal Trainer", "Gerente", "Assistente Geral" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btDelFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAtualizarFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfIdFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNomeGerFun, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfLoginGerFun, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxCargoGerFun, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSenhaGerFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(tfCPFGerFun, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeGerFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPFGerFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoginGerFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenhaGerFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxCargoGerFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfIdFun)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btAtualizarFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btDelFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        mbGerenciar.setText("Gerenciar");

        miCadFun.setText("Cadastrar Funcionário");
        miCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadFunActionPerformed(evt);
            }
        });
        mbGerenciar.add(miCadFun);

        miGerPlan.setText("Gerenciar Planos");
        miGerPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerPlanActionPerformed(evt);
            }
        });
        mbGerenciar.add(miGerPlan);

        miHisPa.setText("Histórico de Pagamentos");
        miHisPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHisPaActionPerformed(evt);
            }
        });
        mbGerenciar.add(miHisPa);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbGerenciar.add(miVoltar);

        menuBarGerente.add(mbGerenciar);

        setJMenuBar(menuBarGerente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadFunActionPerformed
CadastrarFuncionario cadfun = new CadastrarFuncionario();
CJanela.abrir(cadfun, "Cadastro de Funcionários", this);
this.dispose();
    }//GEN-LAST:event_miCadFunActionPerformed

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void btBuscarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarFunActionPerformed
        try {
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarFunActionPerformed

    private void btAtualizarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarFunActionPerformed
 atualizar();
    }//GEN-LAST:event_btAtualizarFunActionPerformed

    private void btDelFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelFunActionPerformed
        try {
            deletar();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarFuncionario.class.getName()).log(Level.SEVERE, null, ex); //esse foi incrementado pela propria IDE
            //entretanto compreendo que antes de deletar deve ter uma SQLException
        }
    }//GEN-LAST:event_btDelFunActionPerformed

    private void miGerPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerPlanActionPerformed
 GerenciarPlanos gerplan = new GerenciarPlanos();
 CJanela.abrir(gerplan, "Tela de Gerenciamento de Planos", this);
 this.dispose();
    }//GEN-LAST:event_miGerPlanActionPerformed

    private void miHisPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHisPaActionPerformed
HistoricoPagamentos hispa = new HistoricoPagamentos();
CJanela.abrir(hispa, "Tela de Gerenciamento de Planos", this);
this.dispose();
    }//GEN-LAST:event_miHisPaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
tabelar();
    }//GEN-LAST:event_formWindowOpened

    
    private void tabelar(){
    try {
        List<Funcionario> lista = dao.tabelaIndividual();
        String[] colunas = { "ID", "Nome", "Cargo", "Login", "Senha"};
        String[] campos = { "id", "nome", "cargo", "login", "senha" };
        STabela.preencherTabela(tabelaFun, lista, colunas, campos);
    } catch (SQLException e) {
        e.printStackTrace(); // Ou exiba uma mensagem de erro
        JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e.getMessage());
    }
}
    
    private void buscar() throws SQLException{
    Funcionario funcionario = dao.read(Integer.parseInt(tfIdFun.getText()));
     if (funcionario == null) {
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        preencherCampos(funcionario);
    tabelar();
    }
    
    private void atualizar() {
    try {
         int numeroCargo = cboxCargoGerFun.getSelectedIndex();
        String cargo = converterNumeroParaCargo(numeroCargo);
        Funcionario funcionario = new Funcionario();  // Busca o funcionário
        funcionario.setId(Integer.parseInt(tfIdFun.getText()));
        funcionario.setNome(tfNomeGerFun.getText());
        funcionario.setCpf(tfCPFGerFun.getText());
        funcionario.setLogin(tfLoginGerFun.getText());
        funcionario.setSenha(tfSenhaGerFun.getText());
        funcionario.setCargo(cargo);
        
         try {
        dao.update(funcionario);
        JOptionPane.showMessageDialog(null, "Funcionário atualizado com sucesso!");
        tfIdFun.setEnabled(true);
        tabelar();
        limparCaixa();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro no banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "ID inválido! Digite um número:", "Erro", JOptionPane.ERROR_MESSAGE);
}
    }
  
    
  private void deletar()throws SQLException{
     int id = Integer.parseInt(tfIdFun.getText());  
    int resposta = JOptionPane.showConfirmDialog(null, "Confirmar exclusão do funcionário?\n" , "Confirmação", JOptionPane.YES_NO_OPTION);
     if (resposta == JOptionPane.YES_OPTION) {
            dao.delete(id);
            JOptionPane.showMessageDialog(null, "Funcionário deletado com sucesso!");
     tabelar(); 
     tfIdFun.setEnabled(true);
}
    }
    private void preencherCampos(Funcionario funcionario) {
        tfIdFun.setEnabled(false);
        tfNomeGerFun.setText(funcionario.getNome());
        tfCPFGerFun.setText(funcionario.getCpf());
        tfLoginGerFun.setText(funcionario.getLogin());
        tfSenhaGerFun.setText(funcionario.getSenha());

    }

    private void limparCaixa(){
        tfIdFun.setText("");
       tfNomeGerFun.setText("");
        tfCPFGerFun.setText("");
        tfLoginGerFun.setText("");
        tfSenhaGerFun.setText("");
    }
    
    private String converterNumeroParaCargo(int numeroCargo) {
    switch (numeroCargo) {
        case 0: return "Secretário";
        case 1: return "Personal Trainer";
        case 2: return "Gerente";
        case 3: return "Assistente Geral";
        default: throw new IllegalArgumentException("Cargo inválido!");
    }
}



    
    public JButton getBtAtualizarFun() {
        return btAtualizarFun;
    }

    public void setBtAtualizarFun(JButton btAtualizarFun) {
        this.btAtualizarFun = btAtualizarFun;
    }

    public JButton getBtBuscarFun() {
        return btBuscarFun;
    }

    public void setBtBuscarFun(JButton btBuscarFun) {
        this.btBuscarFun = btBuscarFun;
    }

    public JButton getBtDelFun() {
        return btDelFun;
    }

    public void setBtDelFun(JButton btDelFun) {
        this.btDelFun = btDelFun;
    }

    public JComboBox<String> getCboxCargoGerFun() {
        return cboxCargoGerFun;
    }

    public void setCboxCargoGerFun(JComboBox<String> cboxCargoGerFun) {
        this.cboxCargoGerFun = cboxCargoGerFun;
    }

    public JTable getTabelaFun() {
        return tabelaFun;
    }

    public void setTabelaFun(JTable tabelaFun) {
        this.tabelaFun = tabelaFun;
    }

    public JTextField getTfCPFGerFun() {
        return tfCPFGerFun;
    }

    public void setTfCPFGerFun(JTextField tfCPFGerFun) {
        this.tfCPFGerFun = tfCPFGerFun;
    }

    public JTextField getTfIdFun() {
        return tfIdFun;
    }

    public void setTfIdFun(JTextField tfIdFun) {
        this.tfIdFun = tfIdFun;
    }

    public JTextField getTfLoginGerFun() {
        return tfLoginGerFun;
    }

    public void setTfLoginGerFun(JTextField tfLoginGerFun) {
        this.tfLoginGerFun = tfLoginGerFun;
    }

    public JTextField getTfNomeGerFun() {
        return tfNomeGerFun;
    }

    public void setTfNomeGerFun(JTextField tfNomeGerFun) {
        this.tfNomeGerFun = tfNomeGerFun;
    }

    public JTextField getTfSenhaGerFun() {
        return tfSenhaGerFun;
    }

    public void setTfSenhaGerFun(JTextField tfSenhaGerFun) {
        this.tfSenhaGerFun = tfSenhaGerFun;
    }

    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarFun;
    private javax.swing.JButton btBuscarFun;
    private javax.swing.JButton btDelFun;
    private javax.swing.JComboBox<String> cboxCargoGerFun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbGerenciar;
    private javax.swing.JMenuBar menuBarGerente;
    private javax.swing.JMenuItem miCadFun;
    private javax.swing.JMenuItem miGerPlan;
    private javax.swing.JMenuItem miHisPa;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tabelaFun;
    private javax.swing.JTextField tfCPFGerFun;
    private javax.swing.JTextField tfIdFun;
    private javax.swing.JTextField tfLoginGerFun;
    private javax.swing.JTextField tfNomeGerFun;
    private javax.swing.JTextField tfSenhaGerFun;
    // End of variables declaration//GEN-END:variables
}
