/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CJanela;
import Controller.CboxExercicio;
import Controller.cboxTreinos;
import JDBC.ConexaoDB;
import java.sql.Connection;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.sql.*;


public class GerenciarTreinos extends javax.swing.JFrame {

    ConexaoDB conexao = new ConexaoDB();
    public GerenciarTreinos() {
        initComponents();
        new CboxExercicio().preencherComboBox(cboxExerGerTrei);
        new cboxTreinos().preencherComboBox(cboxExerGerTrei1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cboxExerGerTrei = new javax.swing.JComboBox<>();
        btExerBusGerTrei = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNomeExer = new javax.swing.JTextField();
        tfGMExer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboxRepetGerTrei = new javax.swing.JComboBox<>();
        cboxSeriesGerTrei = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cboxPesoGerTrei = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTrei = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btAddExer = new javax.swing.JButton();
        btAtualizarTrei = new javax.swing.JButton();
        btDelTrei = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfIdTrei = new javax.swing.JTextField();
        btBuscarTrei = new javax.swing.JButton();
        cboxWeekGerTrei = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btCriarGerTrei = new javax.swing.JButton();
        cboxExerGerTrei1 = new javax.swing.JComboBox<>();
        menuBarTreinador = new javax.swing.JMenuBar();
        mbTreinar = new javax.swing.JMenu();
        miPlanTre = new javax.swing.JMenuItem();
        miGerExer = new javax.swing.JMenuItem();
        miHistoricoAtv = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Exercício");

        cboxExerGerTrei.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxExerGerTrei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxExerGerTrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxExerGerTreiActionPerformed(evt);
            }
        });

        btExerBusGerTrei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExerBusGerTrei.setText("Buscar");
        btExerBusGerTrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExerBusGerTreiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nome");

        tfNomeExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfNomeExer.setForeground(new java.awt.Color(102, 102, 102));
        tfNomeExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeExerActionPerformed(evt);
            }
        });

        tfGMExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfGMExer.setForeground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Grupo Muscular");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("GERENCIAR TREINOS");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Repetições");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Séries");

        cboxRepetGerTrei.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxRepetGerTrei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06", "08", "10", "12", "14", "15", "16", "18", "20" }));

        cboxSeriesGerTrei.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxSeriesGerTrei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "02", "03", "04", "05", "06" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Recomendação de Peso");

        cboxPesoGerTrei.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxPesoGerTrei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40%", "45%", "50%", "55%", "60%", "65%", "70%", "75%", "80%", "85%", "90%", "95%", "100%", "105%", "110%", "115%", "120%" }));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("considere a sua carga máxima.");

        tableTrei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTrei);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Dia da Semana");

        btAddExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAddExer.setText("Adicionar ao Treino ");
        btAddExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddExerActionPerformed(evt);
            }
        });

        btAtualizarTrei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAtualizarTrei.setText("Atualizar Treino");

        btDelTrei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDelTrei.setText("Deletar Treino");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("INFORME O ID DO TREINO");

        tfIdTrei.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIdTrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdTreiActionPerformed(evt);
            }
        });

        btBuscarTrei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBuscarTrei.setText("Buscar Treino");

        cboxWeekGerTrei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" }));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Nome do Treino");

        btCriarGerTrei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCriarGerTrei.setText("Criar Treino");

        cboxExerGerTrei1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxExerGerTrei1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxExerGerTrei1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxExerGerTrei1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAtualizarTrei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDelTrei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAddExer, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(btBuscarTrei, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfIdTrei)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cboxExerGerTrei, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExerBusGerTrei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomeExer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfGMExer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(282, 282, 282)))
                                .addGap(355, 355, 355))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboxExerGerTrei1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxRepetGerTrei, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxWeekGerTrei, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboxSeriesGerTrei, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cboxPesoGerTrei, 0, 1, Short.MAX_VALUE)
                                                .addGap(20, 20, 20))))
                                    .addComponent(btCriarGerTrei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExerBusGerTrei)
                    .addComponent(cboxExerGerTrei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNomeExer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfGMExer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(cboxRepetGerTrei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxSeriesGerTrei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cboxPesoGerTrei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cboxWeekGerTrei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCriarGerTrei)
                    .addComponent(jLabel14)
                    .addComponent(cboxExerGerTrei1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIdTrei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddExer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarTrei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizarTrei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDelTrei))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        mbTreinar.setText("Treinamento");

        miPlanTre.setText("Criar Plano de Treino");
        miPlanTre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPlanTreActionPerformed(evt);
            }
        });
        mbTreinar.add(miPlanTre);

        miGerExer.setText("Gerenciar Exercícios");
        miGerExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerExerActionPerformed(evt);
            }
        });
        mbTreinar.add(miGerExer);

        miHistoricoAtv.setText("Histórico de Atividades");
        miHistoricoAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHistoricoAtvActionPerformed(evt);
            }
        });
        mbTreinar.add(miHistoricoAtv);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbTreinar.add(miVoltar);

        menuBarTreinador.add(mbTreinar);

        setJMenuBar(menuBarTreinador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeExerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeExerActionPerformed

    private void miGerExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerExerActionPerformed
   GerenciarExercicios gerex = new GerenciarExercicios();
    CJanela.abrir(gerex, "Tela de Gerenciar Exercicios", this);
    this.dispose();
    }//GEN-LAST:event_miGerExerActionPerformed

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
 this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void tfIdTreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdTreiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdTreiActionPerformed

    private void btAddExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddExerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddExerActionPerformed

    private void miPlanTreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPlanTreActionPerformed
 CriarPlanoTreino crpltr = new CriarPlanoTreino();
 CJanela.abrir(crpltr, "Interface para Criação de Plano de Treino", this);
 this.dispose();
    }//GEN-LAST:event_miPlanTreActionPerformed

    private void miHistoricoAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHistoricoAtvActionPerformed
 HistoricoAtividades histora = new HistoricoAtividades();
 CJanela.abrir(histora, "Histórico de Atividades dos Alunos", this);
 this.dispose();
    }//GEN-LAST:event_miHistoricoAtvActionPerformed

    private void cboxExerGerTreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxExerGerTreiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxExerGerTreiActionPerformed

    private void cboxExerGerTrei1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxExerGerTrei1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxExerGerTrei1ActionPerformed

    private void btExerBusGerTreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExerBusGerTreiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExerBusGerTreiActionPerformed

    private void buscarExercicio(){
        String nome = cboxExerGerTrei.getSelectedItem().toString();
      tfNomeExer.setText(nome);
     String sql = "SELECT cpf FROM membros WHERE nome = ?";
     try (Connection conn = ConexaoDB.getConnection();
             PreparedStatement psmt = conn.prepareStatement(sql)) {

            psmt.setString(1, nome); 

            ResultSet rs = psmt.executeQuery();

            while (rs.next()) {
                String cpf = rs.getString("cpf");
                tfGMExer.setText(cpf);
                tfNomeExer.setEnabled(false);
                tfGMExer.setEnabled(false);
            }
            rs.close();
        } catch (SQLException e) {
            System.err.println("Erro ao consultar CPF: " + e.getMessage());
        }
    }
    
    
    
    
    
    
    
    
    public JButton getBtAddExer() {
        return btAddExer;
    }

    public void setBtAddExer(JButton btAddExer) {
        this.btAddExer = btAddExer;
    }

    public JButton getBtAtualizarTrei() {
        return btAtualizarTrei;
    }

    public void setBtAtualizarTrei(JButton btAtualizarTrei) {
        this.btAtualizarTrei = btAtualizarTrei;
    }

    public JButton getBtBuscarTrei() {
        return btBuscarTrei;
    }

    public void setBtBuscarTrei(JButton btBuscarTrei) {
        this.btBuscarTrei = btBuscarTrei;
    }

    public JButton getBtCriarGerTrei() {
        return btCriarGerTrei;
    }

    public void setBtCriarGerTrei(JButton btCriarGerTrei) {
        this.btCriarGerTrei = btCriarGerTrei;
    }

    public JButton getBtDelTrei() {
        return btDelTrei;
    }

    public void setBtDelTrei(JButton btDelTrei) {
        this.btDelTrei = btDelTrei;
    }

    public JButton getBtExerBusGerTrei() {
        return btExerBusGerTrei;
    }

    public void setBtExerBusGerTrei(JButton btExerBusGerTrei) {
        this.btExerBusGerTrei = btExerBusGerTrei;
    }

    public JComboBox<String> getCboxExerGerTrei() {
        return cboxExerGerTrei;
    }

    public void setCboxExerGerTrei(JComboBox<String> cboxExerGerTrei) {
        this.cboxExerGerTrei = cboxExerGerTrei;
    }

    public JComboBox<String> getCboxExerGerTrei1() {
        return cboxExerGerTrei1;
    }

    public void setCboxExerGerTrei1(JComboBox<String> cboxExerGerTrei1) {
        this.cboxExerGerTrei1 = cboxExerGerTrei1;
    }

    public JComboBox<String> getCboxPesoGerTrei() {
        return cboxPesoGerTrei;
    }

    public void setCboxPesoGerTrei(JComboBox<String> cboxPesoGerTrei) {
        this.cboxPesoGerTrei = cboxPesoGerTrei;
    }

    public JComboBox<String> getCboxRepetGerTrei() {
        return cboxRepetGerTrei;
    }

    public void setCboxRepetGerTrei(JComboBox<String> cboxRepetGerTrei) {
        this.cboxRepetGerTrei = cboxRepetGerTrei;
    }

    public JComboBox<String> getCboxSeriesGerTrei() {
        return cboxSeriesGerTrei;
    }

    public void setCboxSeriesGerTrei(JComboBox<String> cboxSeriesGerTrei) {
        this.cboxSeriesGerTrei = cboxSeriesGerTrei;
    }

    public JComboBox<String> getCboxWeekGerTrei() {
        return cboxWeekGerTrei;
    }

    public void setCboxWeekGerTrei(JComboBox<String> cboxWeekGerTrei) {
        this.cboxWeekGerTrei = cboxWeekGerTrei;
    }

    public JTable getTableTrei() {
        return tableTrei;
    }

    public void setTableTrei(JTable tableTrei) {
        this.tableTrei = tableTrei;
    }

    public JTextField getTfGMExer() {
        return tfGMExer;
    }

    public void setTfGMExer(JTextField tfGMExer) {
        this.tfGMExer = tfGMExer;
    }

    public JTextField getTfIdTrei() {
        return tfIdTrei;
    }

    public void setTfIdTrei(JTextField tfIdTrei) {
        this.tfIdTrei = tfIdTrei;
    }

    public JTextField getTfNomeExer() {
        return tfNomeExer;
    }

    public void setTfNomeExer(JTextField tfNomeExer) {
        this.tfNomeExer = tfNomeExer;
    }


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarTreinos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddExer;
    private javax.swing.JButton btAtualizarTrei;
    private javax.swing.JButton btBuscarTrei;
    private javax.swing.JButton btCriarGerTrei;
    private javax.swing.JButton btDelTrei;
    private javax.swing.JButton btExerBusGerTrei;
    private javax.swing.JComboBox<String> cboxExerGerTrei;
    private javax.swing.JComboBox<String> cboxExerGerTrei1;
    private javax.swing.JComboBox<String> cboxPesoGerTrei;
    private javax.swing.JComboBox<String> cboxRepetGerTrei;
    private javax.swing.JComboBox<String> cboxSeriesGerTrei;
    private javax.swing.JComboBox<String> cboxWeekGerTrei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mbTreinar;
    private javax.swing.JMenuBar menuBarTreinador;
    private javax.swing.JMenuItem miGerExer;
    private javax.swing.JMenuItem miHistoricoAtv;
    private javax.swing.JMenuItem miPlanTre;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tableTrei;
    private javax.swing.JTextField tfGMExer;
    private javax.swing.JTextField tfIdTrei;
    private javax.swing.JTextField tfNomeExer;
    // End of variables declaration//GEN-END:variables
}
