/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CJanela;
import Controller.MembrosDAO;
import Controller.PlanosDAO;
import Controller.STabela;
import Model.Membro;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class GerenciarAluno extends javax.swing.JFrame {

    MembrosDAO dao = new MembrosDAO();
    private final STabela tabela = new STabela();
    public GerenciarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btDelAlu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlu = new javax.swing.JTable();
        btAtualizarAlu = new javax.swing.JButton();
        btBuscarAlu = new javax.swing.JButton();
        tfIdAlu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEnderecoGerAlu = new javax.swing.JTextField();
        tfTelefoneGerAlu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNomeGerAlu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCPFGerAlu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboxPlanoGerAlu = new javax.swing.JComboBox<>();
        menuBarSecretaria = new javax.swing.JMenuBar();
        mbRecepcionar = new javax.swing.JMenu();
        miCadAlu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btDelAlu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDelAlu.setText("Deletar Aluno");
        btDelAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelAluActionPerformed(evt);
            }
        });

        tabelaAlu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Plano"
            }
        ));
        jScrollPane1.setViewportView(tabelaAlu);

        btAtualizarAlu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAtualizarAlu.setText("Atualizar Aluno");
        btAtualizarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarAluActionPerformed(evt);
            }
        });

        btBuscarAlu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBuscarAlu.setText("Buscar Aluno");
        btBuscarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarAluActionPerformed(evt);
            }
        });

        tfIdAlu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INFORME O ID  DO ALUNO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Telefone");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Endereço");

        tfEnderecoGerAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEnderecoGerAlu.setForeground(new java.awt.Color(102, 102, 102));

        tfTelefoneGerAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTelefoneGerAlu.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nome");

        tfNomeGerAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNomeGerAlu.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("CPF");

        tfCPFGerAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfCPFGerAlu.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("GERENCIANDO ALUNOS");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Plano");

        cboxPlanoGerAlu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxPlanoGerAlu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diária", "Plano SE Mensal", "Plano Black", "Plano Black Anual" }));
        cboxPlanoGerAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPlanoGerAluActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDelAlu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAtualizarAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfIdAlu)
                            .addComponent(btBuscarAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomeGerAlu)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCPFGerAlu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 513, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxPlanoGerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTelefoneGerAlu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEnderecoGerAlu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeGerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPFGerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefoneGerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEnderecoGerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboxPlanoGerAlu))
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfIdAlu)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btAtualizarAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btDelAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        mbRecepcionar.setText("Secretaria");

        miCadAlu.setText("Cadastrar Aluno");
        miCadAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadAluActionPerformed(evt);
            }
        });
        mbRecepcionar.add(miCadAlu);

        jMenuItem1.setText("Registrar Pagamento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mbRecepcionar.add(jMenuItem1);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbRecepcionar.add(miVoltar);

        menuBarSecretaria.add(mbRecepcionar);

        setJMenuBar(menuBarSecretaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void miCadAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadAluActionPerformed
CadastrarAluno cadalu = new CadastrarAluno();
        CJanela.abrir(cadalu, "Tela para Cadastro de Alunos", this);
this.dispose();
    }//GEN-LAST:event_miCadAluActionPerformed

    private void btBuscarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarAluActionPerformed
       try {
            buscarAluno();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarAluActionPerformed

    private void cboxPlanoGerAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPlanoGerAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPlanoGerAluActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
InterfacePagamentos intepa = new InterfacePagamentos();
CJanela.abrir(intepa, "Registro de Pagamentos", this);
this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btAtualizarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarAluActionPerformed
     atualizarAluno();
    }//GEN-LAST:event_btAtualizarAluActionPerformed

    private void btDelAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelAluActionPerformed
     try {
            deletarAluno();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarFuncionario.class.getName()).log(Level.SEVERE, null, ex); //esse foi incrementado pela propria IDE
            //entretanto compreendo que antes de deletar deve ter uma SQLException
        }
    }//GEN-LAST:event_btDelAluActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
tabelar();
    }//GEN-LAST:event_formWindowOpened

    private void buscarAluno() throws SQLException{
        Membro membro = dao.read(Integer.parseInt(tfIdAlu.getText()));
       if(membro == null){
           JOptionPane.showMessageDialog(null, "Aluno não Encontrado(a)", "Aviso", JOptionPane.WARNING_MESSAGE);
           return;
       } 
        preencherCampos(membro);
        tabelar();
    }

    private void deletarAluno() throws SQLException{
        int id = Integer.parseInt(tfIdAlu.getText());  
    int resposta = JOptionPane.showConfirmDialog(null, "Confirmar exclusão do funcionário?\n" , "Confirmação", JOptionPane.YES_NO_OPTION);
     if (resposta == JOptionPane.YES_OPTION) {
            dao.delete(id);
            JOptionPane.showMessageDialog(null, "Funcionário deletado com sucesso!");
     tabelar(); 
     tfIdAlu.setEnabled(true);
}
    }
    
    private void atualizarAluno() {
    try {
        int indicePlano = cboxPlanoGerAlu.getSelectedIndex();
        int idPlano = converteIDparaPlano(indicePlano);
        
        Membro alunoAtualizado = new Membro();
        alunoAtualizado.setId(Integer.parseInt(tfIdAlu.getText()));
        alunoAtualizado.setNome(tfNomeGerAlu.getText());
        alunoAtualizado.setCpf(tfCPFGerAlu.getText());
        alunoAtualizado.setTelefone(tfTelefoneGerAlu.getText());
        alunoAtualizado.setEndereco(tfEnderecoGerAlu.getText());
        alunoAtualizado.setId_plano(idPlano);
        
        MembrosDAO dao = new MembrosDAO();
        dao.update(alunoAtualizado);
        
        JOptionPane.showMessageDialog(null, "Aluno atualizado com sucesso!");
        tabelar();
        limparCaixa();
        tfIdAlu.setEnabled(true);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException | SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    private void preencherCampos(Membro membro){
    tfNomeGerAlu.setText(membro.getNome());
    tfCPFGerAlu.setText(membro.getCpf());
    tfTelefoneGerAlu.setText(membro.getTelefone());
    tfEnderecoGerAlu.setText(membro.getEndereco());
    tfIdAlu.setEnabled(false);
    int indicePlano = converteIDparaPlano(membro.getId_plano());
    cboxPlanoGerAlu.setSelectedIndex(indicePlano);
}
    
    
    private void limparCaixa(){
    tfNomeGerAlu.setText("");
    tfCPFGerAlu.setText("");
    tfTelefoneGerAlu.setText("");
    tfEnderecoGerAlu.setText("");
    tfIdAlu.setText("");
    cboxPlanoGerAlu.setSelectedIndex(0);
    }
    
    
    private void tabelar(){
    try {
        List<Membro> lista = dao.tabelaIndividual();
        String[] colunas = { "ID", "Nome", "CPF", "Telefone", "plano"};
        String[] campos = { "id", "nome", "cpf", "telefone", "id_plano" };
        STabela.preencherTabela(tabelaAlu, lista, colunas, campos);
    } catch (SQLException e) {
        e.printStackTrace(); // Ou exiba uma mensagem de erro
        JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e.getMessage());
    }
}
    
    private int converteIDparaPlano(int indicePlano) {
    switch (indicePlano) {
        case 0: return 1; 
        case 1: return 2; 
        case 2: return 3; 
        case 3: return 4; 
        default: throw new IllegalArgumentException("Plano inválido!");
    }
}
    
    public JButton getBtAtualizarAlu() {
        return btAtualizarAlu;
    }

    public void setBtAtualizarAlu(JButton btAtualizarAlu) {
        this.btAtualizarAlu = btAtualizarAlu;
    }

    public JButton getBtBuscarAlu() {
        return btBuscarAlu;
    }

    public void setBtBuscarAlu(JButton btBuscarAlu) {
        this.btBuscarAlu = btBuscarAlu;
    }

    public JButton getBtDelAlu() {
        return btDelAlu;
    }

    public void setBtDelAlu(JButton btDelAlu) {
        this.btDelAlu = btDelAlu;
    }

    public JComboBox<String> getCboxPlanoGerAlu() {
        return cboxPlanoGerAlu;
    }

    public void setCboxPlanoGerAlu(JComboBox<String> cboxPlanoGerAlu) {
        this.cboxPlanoGerAlu = cboxPlanoGerAlu;
    }

    public JTable getTabelaAlu() {
        return tabelaAlu;
    }

    public void setTabelaAlu(JTable tabelaAlu) {
        this.tabelaAlu = tabelaAlu;
    }

    public JTextField getTfCPFGerAlu() {
        return tfCPFGerAlu;
    }

    public void setTfCPFGerAlu(JTextField tfCPFGerAlu) {
        this.tfCPFGerAlu = tfCPFGerAlu;
    }

    public JTextField getTfEnderecoGerAlu() {
        return tfEnderecoGerAlu;
    }

    public void setTfEnderecoGerAlu(JTextField tfEnderecoGerAlu) {
        this.tfEnderecoGerAlu = tfEnderecoGerAlu;
    }

    public JTextField getTfIdAlu() {
        return tfIdAlu;
    }

    public void setTfIdAlu(JTextField tfIdAlu) {
        this.tfIdAlu = tfIdAlu;
    }

    public JTextField getTfNomeGerAlu() {
        return tfNomeGerAlu;
    }

    public void setTfNomeGerAlu(JTextField tfNomeGerAlu) {
        this.tfNomeGerAlu = tfNomeGerAlu;
    }

    public JTextField getTfTelefoneGerAlu() {
        return tfTelefoneGerAlu;
    }

    public void setTfTelefoneGerAlu(JTextField tfTelefoneGerAlu) {
        this.tfTelefoneGerAlu = tfTelefoneGerAlu;
    }

   
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarAlu;
    private javax.swing.JButton btBuscarAlu;
    private javax.swing.JButton btDelAlu;
    private javax.swing.JComboBox<String> cboxPlanoGerAlu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbRecepcionar;
    private javax.swing.JMenuBar menuBarSecretaria;
    private javax.swing.JMenuItem miCadAlu;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tabelaAlu;
    private javax.swing.JTextField tfCPFGerAlu;
    private javax.swing.JTextField tfEnderecoGerAlu;
    private javax.swing.JTextField tfIdAlu;
    private javax.swing.JTextField tfNomeGerAlu;
    private javax.swing.JTextField tfTelefoneGerAlu;
    // End of variables declaration//GEN-END:variables
}
