/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CJanela;
import Controller.ExerciciosDAO;
import Controller.STabela;
import Model.Exercicio;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Roneide
 */
public class GerenciarExercicios extends javax.swing.JFrame {

private final ExerciciosDAO dao = new ExerciciosDAO();
private final STabela tabela = new STabela();
    public GerenciarExercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaExer = new javax.swing.JTable();
        tfIdEx = new javax.swing.JTextField();
        btBuscarExer = new javax.swing.JButton();
        btAtualizarExer = new javax.swing.JButton();
        btDelExer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNomeExer = new javax.swing.JTextField();
        btCriarExer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfMaquinaExer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboxGMExer = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        menuBarTreinador = new javax.swing.JMenuBar();
        mbTreinar = new javax.swing.JMenu();
        miGerTreinos = new javax.swing.JMenuItem();
        miPlanoTreino = new javax.swing.JMenuItem();
        miHistoricoAtv = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaExer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Máquina", "Grupo Muscular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaExer);

        tfIdEx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIdEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdExActionPerformed(evt);
            }
        });

        btBuscarExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBuscarExer.setText("Buscar Exercício");
        btBuscarExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarExerActionPerformed(evt);
            }
        });

        btAtualizarExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAtualizarExer.setText("Atualizar Exercício");
        btAtualizarExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarExerActionPerformed(evt);
            }
        });

        btDelExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDelExer.setText("Deletar Exercício");
        btDelExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelExerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("INFORME O ID DO EXERCÍCIO");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nome");

        tfNomeExer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNomeExer.setForeground(new java.awt.Color(102, 102, 102));
        tfNomeExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeExerActionPerformed(evt);
            }
        });

        btCriarExer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCriarExer.setText("Criar Exercício");
        btCriarExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarExerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Máquina");

        tfMaquinaExer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMaquinaExer.setForeground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Grupo Muscular");

        cboxGMExer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxGMExer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peitoral", "Costas", "Bíceps", "Triceps", "Ombro", "Panturrilha", "Quadriceps", "Isquiotibiais", "Abdomen", "Glúteos" }));
        cboxGMExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxGMExerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("GERENCIAR EXERCÍCIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeExer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMaquinaExer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxGMExer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btCriarExer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdEx, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarExer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualizarExer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDelExer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNomeExer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfMaquinaExer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboxGMExer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btCriarExer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfIdEx, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarExer, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizarExer, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btDelExer, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mbTreinar.setText("Treinamento");

        miGerTreinos.setText("Gerenciar Treinos");
        miGerTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerTreinosActionPerformed(evt);
            }
        });
        mbTreinar.add(miGerTreinos);

        miPlanoTreino.setText("Criar Plano de Treino");
        miPlanoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPlanoTreinoActionPerformed(evt);
            }
        });
        mbTreinar.add(miPlanoTreino);

        miHistoricoAtv.setText("Historico de Atividades");
        miHistoricoAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHistoricoAtvActionPerformed(evt);
            }
        });
        mbTreinar.add(miHistoricoAtv);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbTreinar.add(miVoltar);

        menuBarTreinador.add(mbTreinar);

        setJMenuBar(menuBarTreinador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void cboxGMExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxGMExerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxGMExerActionPerformed

    private void tfIdExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdExActionPerformed

    private void miGerTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerTreinosActionPerformed
 GerenciarTreinos gerentre = new GerenciarTreinos();
 CJanela.abrir(gerentre, "Tela de Gerenciar Treinos", this);
 this.dispose();
    }//GEN-LAST:event_miGerTreinosActionPerformed

    private void miPlanoTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPlanoTreinoActionPerformed
CriarPlanoTreino crpltr = new CriarPlanoTreino();
 CJanela.abrir(crpltr, "Interface para Criação de Plano de Treino", this);
 this.dispose();
    }//GEN-LAST:event_miPlanoTreinoActionPerformed

    private void tfNomeExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeExerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeExerActionPerformed

    private void btCriarExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarExerActionPerformed
 registrarExercicio();
 tabelar();
 limparCaixa();
    }//GEN-LAST:event_btCriarExerActionPerformed

    private void miHistoricoAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHistoricoAtvActionPerformed
 HistoricoAtividades histora = new HistoricoAtividades();
 CJanela.abrir(histora, "Histórico de Atividades dos Alunos", this);
 this.dispose();
    }//GEN-LAST:event_miHistoricoAtvActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 tabelar();
    }//GEN-LAST:event_formWindowOpened

    private void btBuscarExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarExerActionPerformed
     try {
         buscar();
     } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
     }
    }//GEN-LAST:event_btBuscarExerActionPerformed

    private void btAtualizarExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarExerActionPerformed
atualizarExercicio();
    }//GEN-LAST:event_btAtualizarExerActionPerformed

    private void btDelExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelExerActionPerformed
try{
    deletarExercicio();
} catch(SQLException e) {
        JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_btDelExerActionPerformed

    private void registrarExercicio(){
        try{
           String nome = tfNomeExer.getText();
            String maquina = tfMaquinaExer.getText();
            String grupoMuscular = cboxGMExer.getSelectedItem().toString();
       dao.registrarExercicio(nome, maquina, grupoMuscular);
       JOptionPane.showMessageDialog(this, "Exercicio Cadastrado com Sucesso!");
        }catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
    } 
}
        
     private void atualizarExercicio() {
    try {
        int numeroGM = cboxGMExer.getSelectedIndex();
        String gm = converterNumeroParaGM(numeroGM);
        Exercicio exercicio = new Exercicio();
        exercicio.setId(Integer.parseInt(tfIdEx.getText()));
        exercicio.setNome(tfNomeExer.getText());
        exercicio.setMaquina(tfMaquinaExer.getText());
        exercicio.setGrupoMuscular(gm);
        
        try {
            dao.update(exercicio);
            JOptionPane.showMessageDialog(null, "Exercício atualizado com sucesso!");
            tabelar();
            limparCaixa();
            tfIdEx.setEnabled(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro no banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID inválido! Digite um número:", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void deletarExercicio() throws SQLException{
int id = Integer.parseInt(tfIdEx.getText());
int resposta = JOptionPane.showConfirmDialog(null, "Confirmar exclusão do Exercício?\n" , "Confirmação", JOptionPane.YES_NO_OPTION);
     if (resposta == JOptionPane.YES_OPTION) {
            dao.delete(id);
            JOptionPane.showMessageDialog(null, "Exercício deletado com sucesso!");
     tabelar(); 
     tfIdEx.setEnabled(true);
}
}    
     
private void buscar() throws SQLException{
    Exercicio exercicio = dao.read(Integer.parseInt(tfIdEx.getText()));
    if (exercicio == null) {
            JOptionPane.showMessageDialog(null, "Exercício não encontrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        preencherCampos(exercicio);
    tabelar();
}


    private void limparCaixa(){
    tfNomeExer.setText("");
    tfMaquinaExer.setText("");
    cboxGMExer.setSelectedIndex(0);
            }
    
    
    private void tabelar(){
    try {
        List<Exercicio> lista = dao.tabelaIndividual();
        String[] colunas = { "ID", "Nome", "Máquina", "Grupo Muscular" };
        String[] campos = { "id", "nome", "maquina", "grupoMuscular" };
        STabela.preencherTabela(tabelaExer, lista, colunas, campos);
    } catch (SQLException e) {
        e.printStackTrace(); // Ou exiba uma mensagem de erro
        JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e.getMessage());
    }}

    private void preencherCampos(Exercicio exercicio){
        tfIdEx.setEnabled(false);
        tfNomeExer.setText(exercicio.getNome());
        tfMaquinaExer.setText(exercicio.getMaquina());
    }
    
    private String converterNumeroParaGM(int numeroGM) {
    switch (numeroGM) {
        case 0: return "Peitoral";
        case 1: return "Costas";
        case 2: return "Bíceps";
        case 3: return "Triceps";
        case 4: return "Ombro";
        case 5: return "Panturrilha";
        case 6: return "Quadriceps";
        case 7: return "Isquiotibiais";
        case 8: return "Abdomen";
        case 9: return "Glúteos";
        default: throw new IllegalArgumentException("Grupo Múscular Inválido!");
    }
}
    
    

    public JButton getBtAtualizarExer() {
        return btAtualizarExer;
    }

    public void setBtAtualizarExer(JButton btAtualizarExer) {
        this.btAtualizarExer = btAtualizarExer;
    }

    public JButton getBtBuscarExer() {
        return btBuscarExer;
    }

    public void setBtBuscarExer(JButton btBuscarExer) {
        this.btBuscarExer = btBuscarExer;
    }

    public JButton getBtCriarExer() {
        return btCriarExer;
    }

    public void setBtCriarExer(JButton btCriarExer) {
        this.btCriarExer = btCriarExer;
    }

    public JButton getBtDelExer() {
        return btDelExer;
    }

    public void setBtDelExer(JButton btDelExer) {
        this.btDelExer = btDelExer;
    }

    public JComboBox<String> getCboxGMExer() {
        return cboxGMExer;
    }

    public void setCboxGMExer(JComboBox<String> cboxGMExer) {
        this.cboxGMExer = cboxGMExer;
    }

    public JTable getTabelaExer() {
        return tabelaExer;
    }

    public void setTabelaExer(JTable tabelaExer) {
        this.tabelaExer = tabelaExer;
    }

    public JTextField getTfIdEx() {
        return tfIdEx;
    }

    public void setTfIdEx(JTextField tfIdEx) {
        this.tfIdEx = tfIdEx;
    }

    public JTextField getTfMaquinaExer() {
        return tfMaquinaExer;
    }

    public void setTfMaquinaExer(JTextField tfMaquinaExer) {
        this.tfMaquinaExer = tfMaquinaExer;
    }

    public JTextField getTfNomeExer() {
        return tfNomeExer;
    }

    public void setTfNomeExer(JTextField tfNomeExer) {
        this.tfNomeExer = tfNomeExer;
    }

  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarExercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizarExer;
    private javax.swing.JButton btBuscarExer;
    private javax.swing.JButton btCriarExer;
    private javax.swing.JButton btDelExer;
    private javax.swing.JComboBox<String> cboxGMExer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbTreinar;
    private javax.swing.JMenuBar menuBarTreinador;
    private javax.swing.JMenuItem miGerTreinos;
    private javax.swing.JMenuItem miHistoricoAtv;
    private javax.swing.JMenuItem miPlanoTreino;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tabelaExer;
    private javax.swing.JTextField tfIdEx;
    private javax.swing.JTextField tfMaquinaExer;
    private javax.swing.JTextField tfNomeExer;
    // End of variables declaration//GEN-END:variables
}
