/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CJanela;
import Controller.STabela;
import Model.Plano;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Roneide
 */
public class GerenciarPlanos extends javax.swing.JFrame {

    //funciona normal pode tirar o comentário private final ExerciciosDAO dao = new ExerciciosDAO();
private final STabela tabela = new STabela();
    public GerenciarPlanos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPlanos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btDel = new javax.swing.JButton();
        btAtu = new javax.swing.JButton();
        btCriar = new javax.swing.JButton();
        mbGerenciar = new javax.swing.JMenuBar();
        mb_Gerente = new javax.swing.JMenu();
        miCadFun = new javax.swing.JMenuItem();
        miGerFun = new javax.swing.JMenuItem();
        MiHistoPa = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaPlanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome do Plano", "Valor do Plano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPlanos);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("GERENCIAR PLANOS");

        btDel.setText("Deletar Plano");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btAtu.setText("Atualizar Plano");
        btAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtuActionPerformed(evt);
            }
        });

        btCriar.setText("Criar Plano");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDel)
                    .addComponent(btAtu)
                    .addComponent(btCriar))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        );

        mb_Gerente.setText("Gerenciar");

        miCadFun.setText("Cadastrar Funcionário");
        miCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadFunActionPerformed(evt);
            }
        });
        mb_Gerente.add(miCadFun);

        miGerFun.setText("Gerenciar Funcionário");
        miGerFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerFunActionPerformed(evt);
            }
        });
        mb_Gerente.add(miGerFun);

        MiHistoPa.setText(" Histórico de Pagamentos");
        MiHistoPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiHistoPaActionPerformed(evt);
            }
        });
        mb_Gerente.add(MiHistoPa);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mb_Gerente.add(miVoltar);

        mbGerenciar.add(mb_Gerente);

        setJMenuBar(mbGerenciar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtuActionPerformed
AtualizarPlano atupa = new AtualizarPlano();
        CJanela.abrir(atupa, "Criar Planos", this);
    }//GEN-LAST:event_btAtuActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
CriarPlano cripa = new CriarPlano();
        CJanela.abrir(cripa, "Deletar Planos", this);
    }//GEN-LAST:event_btCriarActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
DeletarPlano detepa = new DeletarPlano();
CJanela.abrir(detepa, "Deletar Planos", this);
    }//GEN-LAST:event_btDelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 tabelar();

    }//GEN-LAST:event_formWindowOpened

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void MiHistoPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiHistoPaActionPerformed
HistoricoPagamentos hispa = new HistoricoPagamentos();
CJanela.abrir(hispa, "Tela de Gerenciamento de Planos", this);
this.dispose();
    }//GEN-LAST:event_MiHistoPaActionPerformed

    private void miGerFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerFunActionPerformed
GerenciarFuncionario geren = new GerenciarFuncionario();
CJanela.abrir(geren,"Tela de Gerênciar Funcionários", this);
this.dispose();
    }//GEN-LAST:event_miGerFunActionPerformed

    private void miCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadFunActionPerformed
CadastrarFuncionario cadfun = new CadastrarFuncionario();
CJanela.abrir(cadfun, "Cadastro de Funcionários", this);
this.dispose();
    }//GEN-LAST:event_miCadFunActionPerformed

    
    private void tabelar(){
    try {
        List<Plano> lista = dao.tabelaIndividual();
        String[] colunas = { "ID", "Nome do Plano", "Valor do Plano"};
        String[] campos = { "id", "nome", "Valor"};
        STabela.preencherTabela(tabelaPlanos, lista, colunas, campos);
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e.getMessage());
    } 
}
    
    
    
    
    
    
    
    
    
    
    
    public JButton getBtAtu() {
        return btAtu;
    }

    public void setBtAtu(JButton btAtu) {
        this.btAtu = btAtu;
    }

    public JButton getBtCriar() {
        return btCriar;
    }

    public void setBtCriar(JButton btCriar) {
        this.btCriar = btCriar;
    }

    public JButton getBtDel() {
        return btDel;
    }

    public void setBtDel(JButton btDel) {
        this.btDel = btDel;
    }

    public JTable getTabelaPlanos() {
        return tabelaPlanos;
    }

    public void setTabelaPlanos(JTable tabelaPlanos) {
        this.tabelaPlanos = tabelaPlanos;
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarPlanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarPlanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarPlanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarPlanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarPlanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MiHistoPa;
    private javax.swing.JButton btAtu;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btDel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mbGerenciar;
    private javax.swing.JMenu mb_Gerente;
    private javax.swing.JMenuItem miCadFun;
    private javax.swing.JMenuItem miGerFun;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tabelaPlanos;
    // End of variables declaration//GEN-END:variables
}
