
package View;

import Controller.CJanela;
import Controller.CboxAluno;

/**
 *
 * @author Roneide
 */
public class HistoricoAtividades extends javax.swing.JFrame {

    /**
     * Creates new form HistoricoAtividades
     */
    public HistoricoAtividades() {
        initComponents();
        new CboxAluno().preencherComboBox(cboxNomeAlunoHistorAtv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistorico = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cboxNomeAlunoHistorAtv = new javax.swing.JComboBox<>();
        btBuscarHistorAtiv = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfIDAlunoHistorAtv = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        menuBarTreinamento = new javax.swing.JMenuBar();
        mbTreinar = new javax.swing.JMenu();
        miCriarPlanTrei = new javax.swing.JMenuItem();
        miGerTrei = new javax.swing.JMenuItem();
        miGerExer = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Aluno", "Plano de Treino", "Data de Inicio", "Tempo de Execução", "ID"
            }
        ));
        jScrollPane1.setViewportView(tableHistorico);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nome do Aluno");

        cboxNomeAlunoHistorAtv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboxNomeAlunoHistorAtv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno 1", "Aluno 2", "Aluno 3", "Aluno 4", " " }));

        btBuscarHistorAtiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btBuscarHistorAtiv.setText("Buscar");
        btBuscarHistorAtiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarHistorAtivActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("ID do Aluno");

        tfIDAlunoHistorAtv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfIDAlunoHistorAtv.setForeground(new java.awt.Color(102, 102, 102));
        tfIDAlunoHistorAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDAlunoHistorAtvActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfIDAlunoHistorAtv))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxNomeAlunoHistorAtv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBuscarHistorAtiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboxNomeAlunoHistorAtv)
                    .addComponent(btBuscarHistorAtiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfIDAlunoHistorAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mbTreinar.setText("Treinamento");

        miCriarPlanTrei.setText("Criar Plano de Treinio");
        miCriarPlanTrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarPlanTreiActionPerformed(evt);
            }
        });
        mbTreinar.add(miCriarPlanTrei);

        miGerTrei.setText("Gerenciar Treinos");
        miGerTrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerTreiActionPerformed(evt);
            }
        });
        mbTreinar.add(miGerTrei);

        miGerExer.setText("Gerenciar Exercicios");
        miGerExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerExerActionPerformed(evt);
            }
        });
        mbTreinar.add(miGerExer);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mbTreinar.add(miVoltar);

        menuBarTreinamento.add(mbTreinar);

        setJMenuBar(menuBarTreinamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarHistorAtivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarHistorAtivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarHistorAtivActionPerformed

    private void tfIDAlunoHistorAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDAlunoHistorAtvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDAlunoHistorAtvActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    private void miGerExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerExerActionPerformed
GerenciarExercicios gerex = new GerenciarExercicios();
    CJanela.abrir(gerex, "Tela de Gerenciar Exercicios", this);
    this.dispose();
    }//GEN-LAST:event_miGerExerActionPerformed

    private void miCriarPlanTreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarPlanTreiActionPerformed
 CriarPlanoTreino crpltr = new CriarPlanoTreino();
 CJanela.abrir(crpltr, "Interface para Criação de Plano de Treino", this);
 this.dispose();
    }//GEN-LAST:event_miCriarPlanTreiActionPerformed

    private void miGerTreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerTreiActionPerformed
 GerenciarTreinos gerentre = new GerenciarTreinos();
 CJanela.abrir(gerentre, "Tela de Gerenciar Treinos", this);
 this.dispose();
    }//GEN-LAST:event_miGerTreiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoAtividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarHistorAtiv;
    private javax.swing.JButton btLimpar;
    private javax.swing.JComboBox<String> cboxNomeAlunoHistorAtv;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mbTreinar;
    private javax.swing.JMenuBar menuBarTreinamento;
    private javax.swing.JMenuItem miCriarPlanTrei;
    private javax.swing.JMenuItem miGerExer;
    private javax.swing.JMenuItem miGerTrei;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTable tableHistorico;
    private javax.swing.JTextField tfIDAlunoHistorAtv;
    // End of variables declaration//GEN-END:variables
}
