
package View;

import Controller.CJanela;
import Controller.CboxAluno;
import View.CadastrarAluno;
import View.GerenciarAluno;


/**
 *
 * @author 12825144744
 */
public class InterfacePagamentos extends javax.swing.JFrame {


    public InterfacePagamentos() {
        initComponents();
        new CboxAluno().preencherComboBox(cboxAlunoPag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboxDescPag = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboxAlunoPag = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfNovoPag = new javax.swing.JTextField();
        tfValorPag = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboxMesPag = new javax.swing.JComboBox<>();
        btEfetuarPagamento = new javax.swing.JButton();
        btEfetuarPagamento1 = new javax.swing.JButton();
        mbSecretaria = new javax.swing.JMenuBar();
        mb_Secretaria = new javax.swing.JMenu();
        miRegAlu = new javax.swing.JMenuItem();
        miGerAlu = new javax.swing.JMenuItem();
        miVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tabela de Pagamentos");

        cboxDescPag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboxDescPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "14", "16", "18", "20" }));
        cboxDescPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDescPagActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Selecione o Desconto");

        cboxAlunoPag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboxAlunoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "14", "16", "18", "20" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Aluno:");

        tfNovoPag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfNovoPag.setForeground(new java.awt.Color(102, 102, 102));
        tfNovoPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNovoPagActionPerformed(evt);
            }
        });

        tfValorPag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfValorPag.setForeground(new java.awt.Color(102, 102, 102));
        tfValorPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorPagActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Valor:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Mês");

        cboxMesPag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboxMesPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        btEfetuarPagamento.setBackground(new java.awt.Color(255, 204, 0));
        btEfetuarPagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEfetuarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btEfetuarPagamento.setText("Buscar Aluno");
        btEfetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEfetuarPagamentoActionPerformed(evt);
            }
        });

        btEfetuarPagamento1.setBackground(new java.awt.Color(255, 204, 0));
        btEfetuarPagamento1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEfetuarPagamento1.setForeground(new java.awt.Color(255, 255, 255));
        btEfetuarPagamento1.setText("EFETUAR PAGAMENTO");
        btEfetuarPagamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEfetuarPagamento1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxAlunoPag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxDescPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfNovoPag)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValorPag)
                            .addComponent(cboxMesPag, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btEfetuarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btEfetuarPagamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAlunoPag)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValorPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addComponent(btEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboxMesPag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboxDescPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNovoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(314, Short.MAX_VALUE)
                    .addComponent(btEfetuarPagamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)))
        );

        mb_Secretaria.setText("Secretaria");

        miRegAlu.setText("Registrar Aluno");
        miRegAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegAluActionPerformed(evt);
            }
        });
        mb_Secretaria.add(miRegAlu);

        miGerAlu.setText("Gerenciar Aluno");
        miGerAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGerAluActionPerformed(evt);
            }
        });
        mb_Secretaria.add(miGerAlu);

        miVoltar.setText("Voltar");
        miVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVoltarActionPerformed(evt);
            }
        });
        mb_Secretaria.add(miVoltar);

        mbSecretaria.add(mb_Secretaria);

        setJMenuBar(mbSecretaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxDescPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDescPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxDescPagActionPerformed

    private void tfNovoPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNovoPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNovoPagActionPerformed

    private void tfValorPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorPagActionPerformed

    private void btEfetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEfetuarPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEfetuarPagamentoActionPerformed

    private void miRegAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegAluActionPerformed
CadastrarFuncionario cadfun = new CadastrarFuncionario();
CJanela.abrir(cadfun, "Cadastro de Funcionários", this);
this.dispose();
    }//GEN-LAST:event_miRegAluActionPerformed

    private void btEfetuarPagamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEfetuarPagamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEfetuarPagamento1ActionPerformed

    private void miGerAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGerAluActionPerformed
GerenciarAluno geralu = new GerenciarAluno();
CJanela.abrir(geralu, "Tela de Gerenciar Alunos", this);
this.dispose();
    }//GEN-LAST:event_miGerAluActionPerformed

    private void miVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVoltarActionPerformed
this.dispose();
    }//GEN-LAST:event_miVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEfetuarPagamento;
    private javax.swing.JButton btEfetuarPagamento1;
    private javax.swing.JComboBox<String> cboxAlunoPag;
    private javax.swing.JComboBox<String> cboxDescPag;
    private javax.swing.JComboBox<String> cboxMesPag;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mbSecretaria;
    private javax.swing.JMenu mb_Secretaria;
    private javax.swing.JMenuItem miGerAlu;
    private javax.swing.JMenuItem miRegAlu;
    private javax.swing.JMenuItem miVoltar;
    private javax.swing.JTextField tfNovoPag;
    private javax.swing.JTextField tfValorPag;
    // End of variables declaration//GEN-END:variables
}
